"""add_approval_status

Revision ID: 2da5f2947d78
Revises: 6afa8aa56757
Create Date: 2026-09-06 05:50:39.151406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2da5f2947d78'
down_revision: Union[str, Sequence[str], None] = '6afa8aa56757'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approval_status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='approvalstatusenum', native_enum=False), nullable=False))
        batch_op.add_column(sa.Column('approved_by_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_users_approved_by_id_users', 'users', ['approved_by_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_users_approved_by_id_users', type_='foreignkey')
        batch_op.drop_column('approved_by_id')
        batch_op.drop_column('approval_status')

    # ### end Alembic commands ###
